name: Deploy Website

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' | ssh-add -
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-add -l
          echo "SSH key added successfully."

      - name: Verify SSH Connection
        run: ssh -o StrictHostKeyChecking=no -T git@github.com || exit 1

      - name: Deploy to Namecheap Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/public_html/
            git pull origin main
            echo "Deployment successful!"
