name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Namecheap
      run: |
        ssh -o "StrictHostKeyChecking=no" elensrtr@162.0.217.88 -p 21098 "cd /home/elensrtr/public_html && git pull origin main"
